project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!/extensions"
    - "!/portfolio (old)"
    - "!/practice-activities/old-labs"
    - "!/practice-activities/student"
    - "!/practice-activities/solutions"

website:
  page-navigation: true
  favicon: images/cat-monsters-horst.png
  title: "Advanced R"
  description: "Homepage for Advanced R at Cal Poly"
  site-url: "https://github.com/atheobold/stat-541-website"
  repo-url: https://github.com/atheobold/stat-541-website
  repo-actions: [issue, edit]

  page-footer:
    left: "This page is built with ❤️ by Drs. Kelly Bodwin & Allison Theobold and also [Quarto](https://quarto.org/)."
    background: "#5D737E"
    right:
    - text: "License"
      href: LICENSE.md

  navbar:
    background: "#5D737E"
    logo: "images/cat-monsters-horst.png"
    alt: "A orange long haired cat curled up in a ball which three round green monsters give it pets."
    align: center
    title: false
    collapse-below: lg

    right:
      - icon: github
        href: https://github.com/atheobold/stat-541-website
        aria-label: GitHub

    left:
      - text: "Overview"
        href: index.qmd
      - text: "Schedule"
        href: course-materials/calendar.qmd
      - text: "Syllabus"
        href: course-materials/syllabus.qmd
      - text: "STAT 331 Review"
        href: 1810-review.qmd
      - text: "Unit 1 - Complex Analyses"
        href: unit-1.qmd
      - text: "Unit 2 - Professional Deliverables"
        href: unit-2.qmd
      - text: "Unit 3 - Package Development"
        href: unit-3.qmd
      - text: "Projects"
        href: project.qmd

  sidebar:
    - id: review
      title: "STAT 331 Review"
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - href: 1810-review.qmd
        - href: 1810-review/setup-workflow.qmd
        - href: 1810-review/ggplot-review.qmd
        - href: 1810-review/dplyr-review.qmd
        - href: 1810-review/tidyr-review.qmd
        - href: 1810-review/quarto-review.qmd
        - href: 1810-review/setup-version-control.qmd
        - text: Week 1 In-Class Activity
          href: practice-activities/week-1.qmd

    - id: unit-1
      title: "Unit 1"
      contents:
        - href: unit-1.qmd
        - href: unit-1/writing-functions.qmd
        - href: unit-1/iterating-functions.qmd
        - href: unit-1/efficient-code.qmd
        - text: "Week 2: In-Class Activity"
          href: practice-activities/week-2.qmd
        - href: unit-1/json-api.qmd
        - href: unit-1/web-scraping.qmd
        - text: "Week 3: In-Class Activity"
          href: practice-activities/week-3.qmd
        - href: unit-1/formatting-tables.qmd
        - href: unit-1/alt-geoms.qmd
        - href: unit-1/styled-plots.qmd
        - text: "Week 4: In-Class Activity"
          href: practice-activities/week-4.qmd

    - id: project
      title: "Project"
      contents:
        - href: project.qmd
        - text: "Week 0: Choose a Dataset"
          href: project/week-0.qmd
        - text: Group Collaboration Expectations
          href: group-stuff/contract.qmd
        - text: "Week 1: Making a Game Plan"
          href: project/week-1.qmd
        - text: "Week 2: Data Summary Functions"
          href: project/week-2.qmd
        - text: "Week 3: Acquiring New Data"
          href: project/week-3.qmd
        - text: "Week 4: Advanced Visualizations"
          href: project/week-4.qmd
        - text: Project 1 Final Deliverable
          href: project/project-1.qmd
        - text: "Week 5: First Draft Dashboard"
          href: project/week-5.qmd
        - text: "Week 6: Dynamic Plots & Country Data"
          href: project/week-6.qmd
        - text: "Week 7: Interactive Dashboard"
          href: project/week-7.qmd
        - text: Project 2 Final Deliverable
          href: project/project-2.qmd
        # - href: project/week-8.qmd
        # - href: project/week-9.qmd
        # - href: project/week-10.qmd
        # - href: project/project-3.qmd

    - id: unit-2
      title: "Unit 2"
      contents:
        - href: unit-2.qmd
        - href: unit-2/quarto-dashboard-static.qmd
        - text: "Week 5: In-Class Activity"
          href: practice-activities/week-5.qmd
        - href: unit-2/ggplot-leaflet.qmd
        - href: unit-2/ggplot-extensions.qmd
        - text: "Week 6: In-Class Activity"
          href: practice-activities/week-6.qmd
        - href: unit-2/quarto-dashboard-dynamic.qmd
        #- text: "Week 7: In-Class Activity"
        #  href: practice-activities/week-7.qmd

    - id: unit-3
      title: "Unit 3"
      contents:
        - href: unit-3.qmd
        - href: unit-3/package-structure.qmd
        - href: unit-3/unit-testing.qmd
        - text: "Week 8: In-Class Activity"
          href: practice-activities/week-8.qmd
        - href: unit-3/debugging.qmd
        - href: unit-3/datatable.qmd
        - text: "Week 9: In-Class Activity"
          href: practice-activities/week-9.qmd
        - href: unit-3/speed.qmd
        - text: "Week 10: In-Class Activity"

format:
  html:
    theme:
      light: [cosmo, style/stat331.scss]
      dark: [cosmo, style/stat331.scss, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    linkcolor: "#5D737E"

editor: visual
    
filters:
- custom-callout
- flourish


custom-callout:
  req-reading:
    icon-symbol: "fa-solid fa-book"
    color: "purple"
  thumbs-up:
    title: "Great job!"
    icon-symbol: "fa-thumbs-up"
    color: "#008000"