---
title: "Project 2 Final Deliverable"
editor: source
---

For this project, you and your group will collaborate to transform your 
report from Project 1 into an interactive Quarto dashboard. Your dashboard will
address a research question related to the original dataset (that you worked 
with for Project 1) and also dig deeper into addressing a related question for 
**one** country.

Along the way you will learn how to:

- create static and dynamic (interactive) dashboards with Quarto,
- craft interactive plots using `plotly` and `leaflet`, and 
- produce dynamic tables using `DT`.

# Final Deliverable

The Quarto dashboard you create _must_ have the following elements:

## Layout 

-   a navigation logo (similar to the Olympic rings)
-   icons to your socials (e.g., LinkedIn, Instagram, Twitter, email)
-   a non-default theme
-   at least two pages
-   at least two tabsets (can be on just one page)

## Static Content

-   at least two cards with quick information (e.g., % of people across the
world who have faith in vaccines)
-   one plot made with `leaflet`
-   one additional interactive plot or table
-   non-default plot colors
-   a summary table displaying the results of a statistical model or summary 
statistics

::: {.column-margin}
::: callout-warning
# Coordinated Colors

The colors in your styled dashboard should match the colors in your plots!
:::
:::

## Interactive (Shiny) Content

-   at least one opportunity for user input via a slide bar
-   at least one opportunity for user input via check boxes

These interactive features are expected to be used to update **at least one** 
table or visualization.

# Peer Review

In Week 7 your group will give (and receive) feedback to another group as it
relates to the layout of the dashboard and the visualizations / tables 
included in the dashboard.

# Submission

Your final submission varies based on the course in which you are enrolled. 
Please see below for the expectations for your course. 

## STAT 431

You are required to submit **both** the link to your GitHub repository
containing your source code **and** a `.zip` folder containing every file needed
to render your dashboard.

## STAT 541

You are required to submit **both** the link to your GitHub repository
containing your source code **and** a link to your [published]{.underline}
dashboard.

<!-- Need to change to Connect Cloud (https://connect.posit.cloud/) instead of  -->

<!-- Shinyapps.io -->

<!-- You are required to submit **both** the link to your GitHub repository  -->

<!-- containing your source code **and** a link to your [published]{.underline} -->

<!-- dashboard. You will need to publish your dashboard through [shinyapps.io](https://www.shinyapps.io/), a free publishing service for content -->

