---
title: "Project 1 Final Deliverable"
editor: source
---

For this project, you and your group will collaborate to produce a stylized,
publication-ready report. The report will include an exploratory data analysis
complete with styled visualizations and polished tables which address
**at least two** research questions posed by your group.

Along the way you will learn how to:

- write data summary functions,
- iterate over those functions,
- acquire data from APIs and webscraping, and
- create professionally styled visualizations and tables.

# Final Deliverable

The final report you create _must_ have the following elements.

## Data Acquisition

-   describes the context of the original data
-   acquire new country-level data using APIs and webscraping
-   joins new data with original data 

## Research Questions

-   addresses **at least two** research questions using the original data 
-   addresses **at least one** research question using the new (country-level)
data

## Data Summaries & Visualizations

-   **at least three** data summaries which address the research questions 
posed
    * **at least one** of these summaries need to be produced with a custom
    function. 
    * **at least one** of these summaries need to include iteration (either 
    inside or outside of a function).

-   creates professionally formatted summary tables (for **all** data summaries)
    * every table **must** have formatted values (e.g., decimals, percentages,
    currencies), boldface headers, and captions, and 
    * **at least one** table must incorporate additional styling (e.g., color, 
    row group labels, spanner labels)
    
-   creates **two** professionally formatted visualizations
    * every visualization **must** have alternative (alt) text, non-default
    colors, a non-default theme, and clear labels
    * **at least one** visualization must use a more complex geometry (e.g.,
    `geom_segment()`, `geom_density_ridge()` `geom_ribbon()`, `geom_tile()`,
    `geom_hex()`)
    
    
## Data Model

-   fits **one** statistical model addressing one of the research questions 
posed
-   professionally formats the output of that model to communicate the results
(must satisfy requirements for professionally formatted tables)

## Quarto Document

::: columns
::: {.column width="55%"}
-   uses a non-default theme
-   uses headers and subheaders to delineate the sections
-   uses table and figure numbers to reference findings
:::

::: {.column width="2%"}
:::

::: {.column width="43%"}
::: callout-warning
# Coordinated Colors

The colors from the document theme you chose should match the colors in your
plots and tables!
:::
:::
:::

# Peer Review

In Week 4 your group will give (and receive) feedback to another group as it
relates to the layout of the report and the visualizations / tables included
in the report. 

# Submission

Your final submission varies based on the course in which you are enrolled. 
Please see below for the expectations for your course. 

## STAT 431

For your final submission, your group will submit **one** GitHub repository
link and **one** HTML document. This means, you will need to choose which group
member's repository will be submitted as the final version. 

## STAT 541

For your final submission, your group will submit **one** GitHub repository
link and **one** link to the published HTML document. This means, you will need
to choose which group member's repository will be submitted as the final
version. 

To publish your document, you will need to sign up for a free [Connect Cloud](https://connect.posit.cloud/) account. I would recommend signing up with
your GitHub account, since the documents you will be publishing for Project 1 
and Project 2 live in a GitHub repository!

Once you've signed up, you need to follow these steps to publish your document:

1. Click on the "Publish" button on the left sidebar
2. Select the "From GitHub" tab
3. Select "Quarto" as the framework
4. Input the URL of your GitHub repository
5. The branch you want to push from should be "main"
6. Input the name of the HTML document you want to publish 
(e.g., `project-1.html`)
7. Select "Publish" to publish your document!

::: callout-tip
# Publish on Push

I would recommend toggling on the "Automatically publish on push" option, so 
your document will automatically update when you push changes to your GitHub
repository. 
:::
