---
title: "Advanced R"
subtitle: "Spring 2026"
tbl-colwidths: [35,15,35,25,25]
---

<!-- Goals:  -->

<!-- - migrate to Google sheets to read in links -->

<!-- - use gt to create spanner rows marking the start of each unit -->

<!-- - hyperlink for unit main page on spanner header? -->

This page contains an outline of the topics, content, and assignments for the quarter. Note that this schedule will be updated as the quarter progresses, with all changes documented here.

+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| Week                                                     | Date      | Coursework                                                                                                              | Lecture Activities                                                                     | Project                                                                         |
+==========================================================+===========+=========================================================================================================================+========================================================================================+=================================================================================+
| **0**                                                    |           |                                                                                                                         |                                                                                        | [Week 0 Project Checkpoint](/project/week-0.qmd)                                |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| ### [Stat 331 Review](1810-review.qmd "Stat 331 Review") | ###       |                                                                                                                         |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **1**                                                    | March 30  | [Installing / Updating R & RStudio](/1810-review/setup-workflow.qmd "Installing / Updating R & RStudio")                | [Week 1 Practice Activity](/practice-activities/week-1.qmd "Week 1 Practice Activity") | [Week 1 Project Checkpoint](/project/week-1.qmd)                                |
|                                                          |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [ggplot Review](/1810-review/ggplot-review.qmd "ggplot Review")                                                         |                                                                                        |                                                                                 |
|                                                          |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [dplyr Review](/1810-review/dplyr-review.qmd "dplyr Review")                                                            |                                                                                        |                                                                                 |
|                                                          |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [tidyr Review](/1810-review/tidyr-review.qmd "tidyr Review")                                                            |                                                                                        |                                                                                 |
|                                                          |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [Quarto review](/1810-review/quarto-review.qmd "Quarto review")                                                         |                                                                                        |                                                                                 |
|                                                          |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [Version Control](/1810-review/setup-version-control.qmd "Version Control")                                             |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| ### [**Unit 1**](unit-1.qmd "Unit 1")                    | ###       |                                                                                                                         |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **2\                                                     | April 6   | [Writing Functions in R](/unit-1/writing-functions.qmd "Writing Functions in R")                                        | [Week 2 Practice Activity](/practice-activities/week-2.qmd "Week 2 Practice Activity") | [Week 2 Project Checkpoint](/project/week-2.qmd "Week 2 Project Checkpoint")    |
| **Function Writing, Iteration & Efficiency               |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [Iterating over Functions](/unit-1/iterating-functions.qmd "Iterating over Functions")                                  |                                                                                        |                                                                                 |
|                                                          |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [Writing Efficient Code](/unit-1/efficient-code.qmd "Writing Efficient Code")                                           |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **3\                                                     | April 13  | [JSON Data & APIs](/unit-1/json-api.qmd "JSON Data & APIs")                                                             | [Week 3 Practice Activity](/practice-activities/week-3.qmd "Week 3 Practice Activity") | [Week 3 Project Checkpoint](/project/week-3.qmd "Week 3 Project Checkpoint")    |
| **JSON Data, APIs & Webscraping                          |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [Webscraping](/unit-2/web-scraping.qmd "Webscraping")                                                                   |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **4**\                                                   | April 20  |                                                                                                                         |                                                                                        | [Week 4 Project Checkpoint](/project/week-4.qmd "Week 4 Project Checkpoint")    |
| Spicing Up Your Visualizations & Tables                  |           |                                                                                                                         |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| ### [**Unit 2**](unit-2.qmd "Unit 2")                    | ###       |                                                                                                                         |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **5**\                                                   | April 27  | [Creating Static Quarto Dashboards](/unit-2/quarto-dashboard-static.qmd "Creating Static Quarto Dashboards")            |                                                                                        | [Week 5 Project Checkpoint](/project/week-5.qmd "Week 5 Project Checkpoint")    |
| Quarto Dashboards (Static)                               |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           |                                                                                                                         |                                                                                        | [Unit 1 Project Due](/project/project-1.qmd "Unit 1 Project Due")               |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **6\                                                     | May 4     | [ggplot Extensions](/unit-2/ggplot-extensions.qmd "ggplot Extensions")                                                  |                                                                                        | [Week 6 Project Checkpoint](/project/week-6.qmd "Week 6 Project Checkpoint")    |
| **Advanced Visualizations & Tables                       |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [leaflet](/unit-2/ggplot-leaflet.qmd "leaflet")                                                                         |                                                                                        |                                                                                 |
|                                                          |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           | [gt & kableExtra](/unit-1/formatting-tables.qmd "gt & kableExtra")                                                      |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| 7\                                                       | May 11    | [Creating Interactive Quarto Dashboards](/unit-2/quarto-dashboard-dynamic.qmd "Creating Interactive Quarto Dashboards") |                                                                                        | [Week 7 Project Checkpoint](/project/week-7.qmd "Week 7 Project Checkpoint")    |
| Quarto Dashboards (Dynamic)                              |           |                                                                                                                         |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| ### [**Unit 3**](unit-3.qmd "Unit 3")                    | ###       |                                                                                                                         |                                                                                        |                                                                                 |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **8**                                                    | May 18    |                                                                                                                         |                                                                                        | [Week 8 Project Checkpoint](/project/week-8.qmd "Week 8 Project Checkpoint")    |
|                                                          |           |                                                                                                                         |                                                                                        |                                                                                 |
|                                                          |           |                                                                                                                         |                                                                                        | [Unit 2 Project Due](/project/project-2.qmd "Unit 2 Project Due")               |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **9**                                                    | May 25    |                                                                                                                         |                                                                                        | [Week 9 Project Checkpoint](/project/week-9.qmd "Week 9 Project Checkpoint")    |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **10**                                                   | June 1    |                                                                                                                         |                                                                                        | [Week 10 Project Checkpoint](/project/week-10.qmd "Week 10 Project Checkpoint") |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
| **Finals Week**                                          | June 9    |                                                                                                                         |                                                                                        | [Unit 3 Project Due](/project/project-3.qmd "Unit 3 Project Due")               |
+----------------------------------------------------------+-----------+-------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+---------------------------------------------------------------------------------+
